# special purpose CI: test against AWS-LC weekly

name: aws-lc

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"

permissions:
  contents: read

env:
  CC: "clang"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install VTest
        run: |
          scripts/build-vtest.sh
      - name: Determine latest AWS-LC release
        id: get_aws_lc_release
        run: |
          result=$(cd .github && python3  -c "from matrix import determine_latest_aws_lc; print(determine_latest_aws_lc(''))")
          echo "::set-output name=result::$result"
      - name: Install AWS-LC
        run: env $${{ steps.get_aws_lc_release.outputs.result }}" scripts/build-ssl.sh
      - name: Compile HAProxy
        run: |
          make DEFINE="-DOPENSSL_API_COMPAT=0x10100000L -DOPENSSL_NO_DEPRECATED" -j3 CC=gcc ERR=1 TARGET=linux-glibc USE_OPENSSL=1
      - name: Run VTest for HAProxy ${{ steps.show-version.outputs.version }}
        id: vtest
        run: |
          # This is required for macOS which does not actually allow to increase
          # the '-n' soft limit to the hard limit, thus failing to run.
          ulimit -n 65536
          make reg-tests VTEST_PROGRAM=../vtest/vtest REGTESTS_TYPES=default,bug,devel
      - name: Show VTest results
        if: ${{ failure() && steps.vtest.outcome == 'failure' }}
        run: |
          for folder in ${TMPDIR}/haregtests-*/vtc.*; do
            printf "::group::"
            cat $folder/INFO
            cat $folder/LOG
            echo "::endgroup::"
          done
          shopt -s nullglob
